### PR TITLE
Python3 installation update

### PR DESCRIPTION
**Pull request by thjsal**

### CODE REVIEW

**Comment by thjsal** [comment]
Installation instruction for Python3 version should be now fixed (MultiNest to be installed from correct source, and installing PyMultiNest using source instead of conda). Also fixed a couple of the small issues regarding links and missing information in some of the examples/tutorials.

**Comment by sguillot** [comment]
Maybe I can add my CALMIP install instructions before we merge the PR ?
Can this wait tomorrow or Friday ?

**Comment by thjsal** [comment]
Sounds fine to me! Those instructions are on a separate page, so it does not actually matter where (in which branch) and in which order we update them. But it can be combined with this if it feels easiest.

**Review by sguillot — APPROVED** [review]

**Review by sguillot — APPROVED** [review]

**Comment by thjsal** [comment]
There were still plenty of warnings when compiling the documentation, but now most of them have been fixed. Especially the references to Riley+2019 in Python docstrings. They seem to work now. If all CI tests pass, I would go forward and merge this branch.

**Pull request merged**
