### PR TITLE
Update contributions

### PR DESCRIPTION
**Pull request by sguillot**
and acknowledgements

### CODE REVIEW

**Review by drannawatts — CHANGES_REQUESTED** [review]
Flip order of Rahul and Lami to preserve alphabetical order? Otherwise looks good!

**Comment by sguillot** [comment]
good catch. I was too fast.

**Review by drannawatts — APPROVED** [review]
Oh yes good additional changes!

**Comment by thjsal** [comment]
I updated also my contact information, and added Pushpita to the community.

**Pull request merged**
