### PR TITLE
Add OGIP standard fits reading

### LINKED ISSUE #194: Provide FITS file implementation of the `CustomInstrument` classes
The CustomInstrument classes provided either in the tutorials or the Zenodo can be confusing. I think it could be greatly simplified by allowing the use to load directly from the FITS files. Response matrices (RMF and ARF) are standardised in X-ray astronomy, so there should not be any complications. It should be also relatively easy to extract the channels edges and to figure out from the file header if the RMF has already been multipled by the ARF or not.

This suggested feature should probably be tackled after the python3 release (since reading FITS file will rely on Astropy, and we will likely face difficulties with astropy version that are only compatible with Python 2)

### PR DESCRIPTION
**Pull request by lmauviard**
This update of the `Data` and `Instrument` class allows to load data from EVT and PHA file and response from ARF/RMF/RSP files.

For the `Instrument` : 
- Lines of 0 are removed automatically
- Removed the mandatory assertion of the channels to be less numerous than the energy edges
- It has been tested on NICER/XMM PN, MOS1, MOS2 ARF/RMF or RSP files

For the `Data` : 
- Allow to load background and compute the associated support
- Allow for phase shift of individual photons
- A generic plotting method is proposed to check the data

@yveskini Can we check the issue you had with this implementation, where you got a line full of random values in the Data ?

Closes #194

### CODE REVIEW

**Comment by lmauviard** [comment]
Error arises from loading astropy during CI tests because it is not installed as a dependency there. I will fix this
I will also try to add it to an example notebook !

**Comment by lmauviard** [comment]
Now also closes #320 because the channels to fit can be requested in the Signal.

**Comment by lmauviard** [comment]
@sguillot This is done and needs reviewing

**Comment by lmauviard** [comment]
Also closes #138

**Comment by lmauviard** [comment]
And #285

**Review by sguillot — APPROVED** [review]

**Comment by thjsal** [comment]
I  suspect that this pull request broke the likelihood checks in the TestRuns in the `examples/examples_modeling_tutorial`. They now fail since the data that they are fitting has been changed.

**Pull request merged**
