### PR TITLE
Updating X-PSI py3 for standard getdist and nestcheck.

### PR DESCRIPTION
**Pull request by thjsal**

### CODE REVIEW

**Comment by thjsal** [comment]
I pushed the fixes found to the problems solved so far when converting X-PSI to be compatible with standard GetDist and NestCheck version, which were discussed in this issue: #170 

More problems still need to be solved though.

**Comment by thjsal** [comment]
Issues mentioned before got solved, but new was found:
https://github.com/xpsi-group/xpsi/issues/170#issuecomment-1384416831

**Comment by thjsal** [comment]
I removed some previously commented or not-used-anymore lines from the `_corner.py` (which need to be put back if later still want to change to the customized nestcheck functionalities)  and expanded the PostProcessing script with pulse and spectral plots. I also copied the new notebook the the documentation pages (since still did not manage to compile documentation properly when reading it from a different path). 

Please, approve, when you think it is ready. Or suggest what else should be changed.

**Comment by yveskini** [comment]
Everything is working fine so far.

**Review by yveskini — APPROVED** [review]

**Pull request merged**
