### PR TITLE
Updates to publications list

### PR DESCRIPTION
**Pull request by drannawatts**
Added links to Salmi et al. 2023, Vinciguerra et al. 2023, 2024, Kini et al. 2024.

### CODE REVIEW

**Comment by yveskini** [comment]
Shouldn't it be  Kini et al. 2023b instead of  Kini et al. 2024?

**Comment by drannawatts** [comment]
Actually no! If you check the MNRAS website carefully you will see that it is going to appear in the first volume of 2024

**Comment by thjsal** [comment]
It looks good to me. A small inconsistency (I think not important to fix) is that Kini 2024 is linked to the published paper, but all the other papers are linked to the corresponding ADS pages.

**Review by thjsal — APPROVED** [review]

**Comment by thjsal** [comment]
There is also this paper from Afle: https://arxiv.org/abs/2304.01035 (but that could be added later as well if needed)

**Comment by drannawatts** [comment]
Yes, right now the ADS link is to the tmp.MNRAS file (which I think will change) so I figured I'd link to the actual paper for now.  When I go in to update the BRAVO paper to the published version I can hopefully update this too (and indeed add Afle, good point!).

**Pull request merged**
