### PR TITLE
Remove py2 documentation from build docs action

### PR DESCRIPTION
**Pull request by drannawatts**
Removed what I think are all of the now irrelevant commands from the build_docs action, have also cross-checked with the neost build_docs action.

One question - should we upgrade micromambav1 to v2? But not sure what this would do.

### CODE REVIEW

**Comment by thjsal** [comment]
I manually ran the Github build docs using this branch and looks like doc building is now working without errors (see the "Actions").  However, the py3 homepages have still this outdated text in it (including a link that is not working anymore):

image

I suggest to update this as well.

**Comment by thjsal** [comment]
So update this file:
https://github.com/xpsi-group/xpsi/blob/main/docs/source/intro.rst

**Comment by drannawatts** [comment]
Removed the warning box (also updated our copyright years!!)

**Review by thjsal — APPROVED** [review]
I think it looks good now! I was just wondering why is the web page not properly updating when I run the build docs action manually. But I now realized it must be so because the action itself is checking out the main branch, and this update is not yet there. So I think we can just merge it and it should work after that.

**Pull request merged**
