### PR TITLE
[WIP ]Create initial version of CI GitHub Action

### PR DESCRIPTION
**Pull request by dhuppenkothen**
This pull request will eventually have a file that automatically runs a GitHub action to run the unit tests. Not for merging yet, because I need to make it actually work first, and I can only do that with an open pull request.

### CODE REVIEW

**Comment by sguillot** [comment]
So that last line of the yml will run all the tests/test*.py automatically right ?

**Comment by dhuppenkothen** [comment]
That's the idea, but the current version doesn't run on all branches and pull requests yet. Still have to set that up.

**Comment by dhuppenkothen** [comment]
Before this is ready for merging, I'll also squash the many silly one-line commits that I made to debug GitHub actions (each time you want to rerun Github Actions, you have to push a commit)

**Comment by dhuppenkothen** [comment]
Messed up the squashing of commits, so will close this and open a new one

**Pull request closed without merging**
