### PR TITLE
requirements for cython version

### PR DESCRIPTION
**Pull request by sguillot**
in environment yml files, and in installation documentation.

### CODE REVIEW

**Comment by sguillot** [comment]
What I haven't tested is to create an environments with `cython = 3.0` and try to install X-PSI to double-check if the requirement in the `setup.py` catches it.

**Review by thjsal — APPROVED** [review]
Without actually testing it, it looks ok to me and I think it could be merged.

**Comment by thjsal** [comment]
I now tested if the `setup.py` catches the cython requirement (if creating environment with wrong cython version), and it seems to me that it does not, since requirement catching (in general) is not working for me. I get this warning:

```
Cython.__version__ == 3.0.0
Using Cython to build extension from .pyx files...
/home/tuomo/anaconda2/envs/xpsi_py3_test/lib/python3.11/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
```
Upgrading setuptools using `pip install --upgrade setuptools` or `pip install --use-pep517 --upgrade setuptools` did not help.

**Comment by thjsal** [comment]
Maybe this is because installing with setup.py is anyway a deprecated method? I suggest we could still merge this since the correct Cython version is now already there when creating the conda environment. But I see now that installation instructions for HPC systems need to still be updated when not using `basic_environment.yml` to make sure not using too new Cython version. I can do that soon.

Anyway, I removed the closing of the linked issue, since this is only a temporary solution (X-PSI should be preferably fixed to work with Cython3), and versions for Numpy, etc., as mentioned in the issue, should probably be specified as well.

**Comment by thjsal** [comment]
Ah, I see now that you actually already fixed the documentation for HPC installation as well. So it looks good to me then.

**Pull request merged**
