### PR TITLE
Py3 redo the intro pages install page 205

### PR DESCRIPTION
**Pull request by Basdorsman**
Installation instruction page for Python 3 is significantly streamlined. Updates to Multinest installation. Updates to Mac OS tips. Basic_environment.yml is now environment.yml.

### CODE REVIEW

**Comment by Basdorsman** [comment]
I have reintroduced "basic_environment.yml" because without it the CI tests fail. Tuomo also mentioned he is using it for installation on HPC systems. I figured we can keep it for now but it would be more streamlined if we have fewer environment.yml files.

**Comment by Basdorsman** [comment]
I'm checking now if the full installation works, also given that I am using a JohannesBuchner Multinest version rather than FarhanFeroz version as in the old installation instructions.

**Review by sguillot — CHANGES_REQUESTED** [review]
- There is a broken RST link to Multinest in `which may be installed later (refer to ...`
- Change the reference to `gsl-latest/build` to something like "Enter the untared directory and type ./configure...

**Comment by Basdorsman** [comment]
add path for gsl also

**Comment by yveskini** [comment]
Removing the Post-processing packages in the environment makes its creation much faster. 
 The removed  Post-processing packages could simply be install by conda-forge.

**Comment by Basdorsman** [comment]
@sguillot would you be available to do a final review before merge?

**Comment by thjsal** [comment]
In case worth to mention here, I installed emcee using this command: `conda install -c conda-forge emcee`

**Comment by sguillot** [comment]
I will implement some small changes.

**Comment by sguillot** [comment]
@Basdorsman  if you find instructions to install BLAS, LAPACK, etc, can you add them ?

The rest is good for merge I think

**Review by sguillot — APPROVED** [review]

**Pull request merged**
